app/models.py
import enum
from datetime import datetime

from app import db


class PredictionType(enum.Enum):
    Aluminio = 0
    Carton = 1
    Contenedor_Plastico = 2
    Organico = 3
    Papel = 4
    Tetra_Pak = 5
    Vidrio = 6


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    last_name = db.Column(db.String(64))
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return '<User {}>'.format(self.username)


class PredictionRecord(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    datetime = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    prediction_type = db.Column(db.Enum(PredictionType))
    confidence = db.Column(db.Float)
    isAccurate = db.Column(db.Boolean, default=None)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref=db.backref('predictions', lazy='dynamic'))

    def __repr__(self):
        return '<PredictionRecord {}>'.format(self.prediction_type)

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap5
from flask_sqlalchemy import SQLAlchemy

from config import Config

db = SQLAlchemy()

bootstrap = Bootstrap5()


def create_app(config_class=Config):

    app = Flask(__name__, template_folder='templates', static_folder='static')
    app.config.from_object(config_class)
    db.init_app(app)
    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import datetime

from flask import render_template, jsonify

from app.main import bp
from app.models import PredictionRecord, User
from app import db


@bp.route('/')
def dashboard():
    users = User.query.count()
    predictions = PredictionRecord.query.count()
    average_confidence = PredictionRecord.query.with_entities(db.func.avg(PredictionRecord.confidence)).scalar()
    all_confidence = PredictionRecord.query.with_entities(PredictionRecord.confidence).all()
    average_confidence = round(average_confidence, 2)
    all_confidence = [confidence[0] for confidence in all_confidence]
    standard_deviation = round((sum([(confidence - average_confidence) ** 2 for confidence in all_confidence]) / (len(
        all_confidence) - 1)) ** 0.5, 2)

    predicitons_with_feedback = PredictionRecord.query.filter(PredictionRecord.isAccurate != None).count()

    correct_predictions = PredictionRecord.query.filter_by(isAccurate=True).count()
    correct_predictions_percentage = round(correct_predictions / predicitons_with_feedback * 100, 2)

    return render_template("dashboard.html", title="Dashboard", users=users, predictions=predictions,
                           average_confidence=average_confidence, standard_deviation=standard_deviation,
                           correct_predictions_percentage=correct_predictions_percentage)


@bp.route("/dashboard/statistics_per_day", methods=["GET"])
def statistics_per_day():
    records = PredictionRecord.query.with_entities(
        db.func.date(PredictionRecord.datetime),
        db.func.count(PredictionRecord.datetime)).group_by(
        db.func.date(PredictionRecord.datetime)).all()

    results_array = []
    for record in records:
        results = {"datetime": record[0], "count": record[1]}
        results_array.append(results)

    return jsonify(results_array)


@bp.route("/dashboard/users_per_day", methods=["GET"])
def users_per_day():
    records = User.query.with_entities(
        db.func.date(User.created_at),
        db.func.count(User.created_at)).group_by(
        db.func.date(User.created_at)).where(
        User.created_at >= f'{datetime.datetime.utcnow() - datetime.timedelta(days=7)}').all()

    results_array = []
    for record in records:
        results = {"datetime": record[0], "count": record[1]}
        results_array.append(results)

    return jsonify(results_array)


@bp.route("/dashboard/predictions_per_type", methods=["GET"])
def predictions_per_type():
    records = PredictionRecord.query.with_entities(
        PredictionRecord.prediction_type,
        db.func.count(PredictionRecord.prediction_type)).group_by(
        PredictionRecord.prediction_type).all()

    results_array = []
    for record in records:
        results = {"type": record[0].name, "count": record[1]}
        results_array.append(results)

    return jsonify(results_array)


@bp.route("/dashboard/percentage_accurate_predictions/<prediction_type>", methods=["GET"])
def percentage_accurate_predictions(prediction_type):
    predicitons_with_feedback = PredictionRecord.query.filter(PredictionRecord.isAccurate != None, PredictionRecord.prediction_type == prediction_type).count()
    correct_predictions = PredictionRecord.query.filter_by(isAccurate=True, prediction_type=prediction_type).count()
    try:
        correct_predictions_percentage = round(correct_predictions / predicitons_with_feedback * 100, 2)
    except ZeroDivisionError:
        correct_predictions_percentage = "No hay datos suficientes"

    return jsonify(correct_predictions_percentage)

app/templates/base.html
<!doctype html>
{% from 'bootstrap5/nav.html' import render_nav_item %}
{% from 'bootstrap5/utils.html' import render_messages %}

<html lang="en">
<head>
    {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Dashboard</title>
        {% block styles %}
            <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}
            <link href="../static/stylesheets/style.css" rel="stylesheet"/>
        {% endblock %}

        <link rel="manifest" href="/manifest.json">
        <meta name="theme-color" content="#ffffff">
    {% endblock %}
</head>
<body class="blackish">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.dashboard') }}">
            Dashboard
        </a>
        <ul class="navbar-nav navbar-left">
        </ul>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="https://github.com/JuanC-Fandino"
                                        target="_blank">GitHub</a></li>
            </ul>
        </div>
    </div>
</nav>
<main class="container content_container">
    {{ render_messages(container=False, dismissible=True) }}
    {% block content %}{% endblock %}
</main>
<footer class="footer mt-auto py-3 bg-dark">
    <div class="container text-center d-flex flex-column">
        <span class="text-muted">Juan Camilo Fandiño Orjuela</span>
        <span class="text-muted">© 2022</span>
    </div>
</footer>

{% block scripts %}
    {{ bootstrap.load_js() }}
    <script src="../static/js/jquery-3.6.1.min.js"></script>
{% endblock %}
</body>
</html>

app/templates/dashboard.html
{% extends 'base.html' %}
{% from 'bootstrap5/utils.html' import render_icon %}

{% block content %}
    <link href="../static/stylesheets/more_info.css" rel="stylesheet"/>
    <h5 class="card-header text-secondary"></h5>

    <div class="d-flex justify-content-between mb-1">
        <h1 class="text-center mb-4">
            Estadísticas Generales
        </h1>
        <img src="../static/images/logo.svg" alt="estadisticas" width="50" height="50">
    </div>


    <div class="whole-container">
        <div class="card">
            <div class="card-body text-black">
                <p class="kpi-label">
                    Usuarios registrados
                </p>
                <p class="kpi">{{ users }}</p>
            </div>
        </div>
        <div class="card">
            <div class="card-body text-black">
                <p class="kpi-label">
                    Predicciones totales
                </p>
                <p class="kpi">{{ predictions }}</p>
            </div>
        </div>

        <div class="card">
            <div class="text-black">
                <div id="usersPlot" class="custom-plot"></div>
            </div>
        </div>

        <div class="card">
            <div class="text-black">
                <div id="myPlot" class="custom-plot"></div>
            </div>
        </div>


        <div class="card">
            <div class="card-body text-black">
                <p class="kpi-label">
                    Confianza promedio
                </p>
                <p class="kpi">{{ average_confidence | round(2) }}%</p>
            </div>
        </div>
        <div class="card">
            <div class="card-body text-black">
                <p class="kpi-label">
                    Desviación estandar (Confianza)
                </p>
                <p class="kpi">{{ standard_deviation | round(2) }}</p>
            </div>
        </div>

        <div class="card" style="height: min-content">
            <div class="card-body text-black">
                <p class="kpi-label">
                    Porcentaje de predicciones correctas
                </p>
                <p class="kpi">{{ correct_predictions_percentage }}%</p>
            </div>

            <div id="custom_type" class="card" style="height: min-content; display: none">
                <div class="card-body text-black">
                    <p id="type_label" class="kpi-label">
                    </p>
                    <p id="type_value" class="kpi"></p>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="text-black">
                <div id="predictionsPlot" class="custom-plot"></div>
            </div>
        </div>


    </div>


{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="../static/js/plotly-2.14.0.min.js"></script>
    <script src="../static/js/dashboard.js"></script>
{% endblock %}